baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #49273'
disableKinds = ['rss','sitemap','taxonomy','term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true


[languages.en]
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
weight = 1

[languages.fr]
languageCode = 'fr-FR'
languageDirection = 'ltr'
languageName = 'Français'
weight = 2

[[cascade]]
[cascade.build]
list = 'never'
render = 'never'
[cascade._target]
path = '/errors'

[[cascade]]
[cascade.build]
list = 'never'
[cascade._target]
path = '/errors/**'
