baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #49013'
disableKinds = ['rss','sitemap','taxonomy','term']

[[segments.root.excludes]]
path = '{/blog,/blog/**}'

[[segments.blog.includes]]
path = '{/blog,/blog/**}'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[[menus.main]]
name = 'Products'
pageRef = '/products'
weight = 30

[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 40
