disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages.en]
  baseURL = 'https://en.example.org/subdir/'
  disabled = false
  weight = 1

[languages.de]
  baseURL = 'https://de.example.org/subdir/'
  disabled = false
  weight = 2

[uglyurls]
  s1 = true

[markup.asciidocext]
  extensions           = ['asciidoctor-diagram']
  workingFolderCurrent = true

  [markup.asciidocext.attributes]
    diagram-cachedir = 'resources/_gen/asciidoctor/diagrams'
    diagram-cache-images-option = true

[security.exec]
  allow = ['^((dart-)?sass|git|go|npx|postcss|tailwindcss|asciidoctor)$']
