baseURL = 'https://example.org/subdir/'
disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages.en]

  disabled = false
  weight = 1

[languages.de]

  disabled = true
  weight = 2

[uglyurls]
  s1 = true

[markup.asciidocext]
  extensions           = ['asciidoctor-diagram']
  workingFolderCurrent = true

[security.exec]
  allow = ['^((dart-)?sass|git|go|npx|postcss|tailwindcss|asciidoctor)$']

[caches.misc]
  dir = ':cacheDir/:project'
