disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

# resourcedir = "xxx"

[languages.en]
  baseURL = 'https://en.example.org/subdir/'
  disabled = false
  weight = 1

[languages.de]
  baseURL = 'https://de.example.org/subdir/'
  disabled = false
  weight = 2

[uglyurls]
  s1 = true

[markup.asciidocext]
  extensions           = ['asciidoctor-diagram']
  workingFolderCurrent = true

[security.exec]
  allow = ['^((dart-)?sass|git|go|npx|postcss|tailwindcss|asciidoctor)$']

[caches.misc]
  dir = ':cacheDir/:project'
