[[redirects]]
from = '/fr/**'
to = '/fr/404.html'
status = 404

[[redirects]] # Default language must be last.
from = '/**'
to = '/en/404.html'
status = 404

# If defaultContentLanguageInSubdir is false, do this instead:

# [[redirects]]
# from = '/fr/**'
# to = '/fr/404.html'
# status = 404

# [[redirects]] # Default language must be last.
# from = '/**'
# to = '/404.html'
# status = 404
