name: Build and test workflow
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install hugo
        run: |
          export HUGO_VERSION=0.118.2
          curl -fSL -o hugo.deb "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
          sudo dpkg -i hugo.deb

      - name: Install Ruby and the gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Generate website
        run: hugo --minify

      - name: Run HTMLProofer
        run:
          bundle exec htmlproofer public/
            --allow-missing-href  true
            --checks              Links,Images,Scripts,Favicon,OpenGraph
            --disable-external    true
            --enforce-https       false
            --ignore-empty-mailto true

      - name: End-2-end tests
        run: |
          hugo server --disableBrowserError --disableFastRender --disableLiveReload &
          npm run cy:ci
